<?php

/**
 * @file
 * Module file for the GDPR Tasks module.
 */

use Drupal\Core\Url;
use Drupal\gdpr_fields\Controller\GDPRController;
use Drupal\Core\Entity\EntityInterface;
use Drupal\user\UserInterface;
use Drupal\Component\Utility\Random;

/**
 * Implements hook_toolbar().
 */
function gdpr_tasks_toolbar() {
  $user = \Drupal::currentUser();

  $items = [];
  $items['gdpr'] = [
    '#cache' => [
      'contexts' => [
        'user',
      ],
    ],
  ];

  if ($user->hasPermission('view gdpr tasks')) {
    $links = [
      'summary' => [
        'title' => t('Summary'),
        'url' => Url::fromRoute('gdpr_tasks.summary'),
        'attributes' => [
          'title' => t('GDPR Summary'),
        ],
      ],
      'tasks' => [
        'title' => t('Tasks'),
        'url' => Url::fromRoute('entity.gdpr_task.collection'),
        'attributes' => [
          'title' => t('GDPR Task list'),
        ],
      ],
    ];
    $items['gdpr'] += [
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => t('GDPR'),
        '#url' => Url::fromRoute('gdpr_tasks.summary'),
        '#attributes' => [
          'title' => t('GDPR'),
          'class' => ['toolbar-icon', 'toolbar-icon-shortcut'],
        ],
      ],
      'tray' => [
        'links' => [
          '#theme' => 'links',
          '#links' => $links,
          '#attributes' => [
            'class' => ['toolbar-menu'],
          ],
        ],
      ],
      '#weight' => -10,
      '#attached' => [
        'library' => [
          'shortcut/drupal.shortcut',
        ],
      ],
    ];
  }

  return $items;
}

/**
 * Implements hook_theme().
 */
function gdpr_tasks_theme() {
  $theme = [];
  $theme['gdpr_task'] = [
    'render element' => 'elements',
    'file' => 'gdpr_task.page.inc',
    'template' => 'gdpr_task',
  ];
  $theme['gdpr_task_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'gdpr_task.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function gdpr_tasks_theme_suggestions_gdpr_task(array $variables) {
  $suggestions = [];
  /* @var \Drupal\gdpr_tasks\Entity\TaskInterface $entity */
  $entity = $variables['elements']['#gdpr_task'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'gdpr_task__' . $sanitized_view_mode;
  $suggestions[] = 'gdpr_task__' . $entity->bundle();
  $suggestions[] = 'gdpr_task__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'gdpr_task__' . $entity->id();
  $suggestions[] = 'gdpr_task__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

function gdpr_tasks_generate_sar_report(UserInterface $user) {
  /* @var \Drupal\gdpr_fields\Controller\GDPRController $controller */
  $controller = \Drupal::classResolver()->getInstanceFromDefinition(GDPRController::class);

  return $controller->rtaData($user);
}

/**
 * Implements hook_entity_presave().
 *
 * Process data for task requests.
 * @todo Consider creating plugin or event listeners for task processing.
 */
function gdpr_tasks_entity_presave(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'gdpr_task') {
    return;
  }

  /* @var \Drupal\gdpr_tasks\Entity\TaskInterface $entity */
  switch ($entity->bundle()) {
    case 'gdpr_remove':
      break;

    // Collect relevant data and save to downloadable csv.
    case 'gdpr_sar':
      if (empty($entity->get('sar_export')->fid)) {
        /* @var \Drupal\file\Plugin\Field\FieldType\FileFieldItemList $field */
        $field = $entity->get('sar_export');
        /* @var \Drupal\Core\Field\FieldDefinitionInterface $field_definition */
        $field_definition = $field->getFieldDefinition();
        $settings = $field_definition->getSettings();

        $config = [
          'field_definition' => $field_definition,
          'name' => $field->getName(),
          'parent' => $field->getParent(),
        ];
        /* @var \Drupal\file\Plugin\Field\FieldType\FileItem $field_type */
        $field_type = Drupal::service('plugin.manager.field.field_type')->createInstance($field_definition->getType(), $config);

        // Prepare destination.
        $dirname = $field_type->getUploadLocation();
        file_prepare_directory($dirname, FILE_CREATE_DIRECTORY);

        // Generate a file entity.
        $random = new Random();
        $destination = $dirname . '/' . $random->name(10, TRUE) . '.csv';

        $user = $entity->getOwner();
        $data = gdpr_tasks_generate_sar_report($user);

        // @todo Add headers to csv export.
        $file = file_save_data('', $destination, FILE_EXISTS_ERROR);

        // Update csv with actual data.
        $fp = fopen($destination, 'w');
        foreach($data as $line){
          fputcsv($fp, $line);
        }
        fclose($fp);

        $values = [
          'target_id' => $file->id(),
          'display' => (int) $settings['display_default'],
          'description' => '',
        ];

        $entity->sar_export = $values;
      }
      break;
  }
}